In [2]:
import numpy as np


In [ ]:
# A) Crear arrays, dtype, shape
a = np.array([1, 2, 3], dtype=np.int32)
b = np.zeros((2,3))
c = np.ones((3,3), dtype=np.int16)
d = np.eye(4)
e = np.arange(0, 10, 2)
f = np.empty((2, 2))

a.dtype, b.shape, c.shape, a, b, c, d, e.shape, f

(dtype('int32'),
 (2, 3),
 (3, 3),
 array([1, 2, 3], dtype=int32),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=int16),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 (5,),
 array([[1., 1.],
        [1., 1.]]))

In [ ]:
# B) Indexación y slicing (incluye vista vs copia)
arr = np.arange(10)
print(arr)

segment = arr[2:7]
print(segment)

segment[:] = 99
print(segment)

arr_copy = arr[2:7].copy()
arr_copy[:] = -1

print(arr_copy)
print(arr)
print(segment)


[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[99 99 99 99 99]
[-1 -1 -1 -1 -1]
[ 0  1 99 99 99 99 99  7  8  9]
[99 99 99 99 99]


In [ ]:
# C) Broadcasting sencillo
M = np.arange(1,10).reshape(3,3)
print(M)
print("#"*10)
# 2 primeras filas
print(M[:2])
print("#"*10)
# ultima columna
print(M[:, -1])
print("#"*10)
# la submatriz inferior-izquierda 2×2
print(M[1:, 1:])

# por q no puede ser M[1:][1:]



[[1 2 3]
 [4 5 6]
 [7 8 9]]
##########
[[1 2 3]
 [4 5 6]]
##########
[3 6 9]
##########
[[5 6]
 [8 9]]


In [66]:
# D) Transposición y productos
X = np.arange(1,11).reshape(5,2)    # 5x2
XT = X.T                             # 2x5
G = XT @ X                           # 2x2 (gram matrix)
dot1 = X[0] @ X[0]                   # norma^2 de la primera fila
X, XT, XT.shape, G, dot1

(array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]),
 array([[ 1,  3,  5,  7,  9],
        [ 2,  4,  6,  8, 10]]),
 (2, 5),
 array([[165, 190],
        [190, 220]]),
 np.int64(5))

In [69]:
# E) Ufuncs y where
v = np.linspace(-2, 2, 5)   # [-2,-1,0,1,2]
sq = np.sqrt(np.abs(v))     # raíz de positivos
print(v)
w = np.array([10,20,30,40,50])
sel = np.where(v >= 0, w, 0)  # si v>=0 toma w, si no 0
sq, sel

[-2. -1.  0.  1.  2.]


(array([1.41421356, 1.        , 0.        , 1.        , 1.41421356]),
 array([ 0,  0, 30, 40, 50]))

In [40]:
# Crea S con enteros aleatorios en [0, 100) y convierte a float32

s = np.random.uniform(0, 100, size=(100,4)).astype(np.float32)
s


array([[53.504536  , 92.42879   , 58.58462   , 35.7459    ],
       [86.63501   ,  3.8574026 , 75.06019   , 93.478584  ],
       [57.20928   , 29.088072  , 53.2525    , 55.361416  ],
       [84.302086  , 14.558437  , 26.893423  , 84.87159   ],
       [84.82328   , 26.465836  , 74.46699   , 15.355912  ],
       [21.753878  , 22.254854  , 57.781303  , 55.32208   ],
       [28.515656  , 78.062004  , 28.327866  , 20.963741  ],
       [90.30284   ,  8.478537  , 47.600098  , 17.761415  ],
       [23.917166  , 66.25922   , 53.685894  , 83.979614  ],
       [66.7069    , 30.654566  , 13.523763  ,  8.509677  ],
       [72.149765  , 90.9547    , 98.022316  , 85.61499   ],
       [99.044365  ,  4.631033  , 11.633206  , 42.78962   ],
       [19.177763  , 24.894812  , 15.349531  , 48.59894   ],
       [ 1.7341299 , 30.865858  , 10.805268  , 97.29667   ],
       [94.90685   , 74.00672   , 39.079117  , 50.893982  ],
       [70.759315  ,  4.7717185 , 44.667465  , 68.70754   ],
       [16.029736  , 78.

In [41]:
# Centra cada columna restando su media y escala por su desviación típica (z-score)

media_col = np.mean(s, axis=0)
media_fil = np.mean(s, axis=1)
std_col = np.std(s, axis=0, ddof=1)

z = (s - media_col) / (std_col)
z


array([[ 3.24024893e-02,  1.37623954e+00,  3.32699478e-01,
        -6.81520462e-01],
       [ 1.16083503e+00, -1.45057499e+00,  9.12790179e-01,
         1.39873648e+00],
       [ 1.58586979e-01, -6.45321429e-01,  1.44959986e-01,
         2.52769832e-02],
       [ 1.08137500e+00, -1.10904443e+00, -7.83120632e-01,
         1.08860433e+00],
       [ 1.09912705e+00, -7.29011834e-01,  8.91904116e-01,
        -1.41622412e+00],
       [-1.04903316e+00, -8.63408089e-01,  3.04415345e-01,
         2.38595642e-02],
       [-8.18725228e-01,  9.17714119e-01, -7.32615173e-01,
        -1.21415961e+00],
       [ 1.28576231e+00, -1.30308843e+00, -5.40562458e-02,
        -1.32954764e+00],
       [-9.75350976e-01,  5.41020334e-01,  1.60219461e-01,
         1.05646420e+00],
       [ 4.82078493e-01, -5.95325768e-01, -1.25385499e+00,
        -1.66291153e+00],
       [ 6.67463839e-01,  1.32919300e+00,  1.72126722e+00,
         1.11539102e+00],
       [ 1.58350086e+00, -1.42588401e+00, -1.32041991e+00,
      

In [54]:
# Construye la matriz de covarianzas 4×4 usando solo operaciones de NumPy (sin np.cov), partiendo de los datos z-score.

n = s.shape[0]
zt = z.T

cov = (zt @ z) / (n - 1)
cov, n



(array([[ 0.99999994, -0.18085079,  0.14706229, -0.15708376],
        [-0.18085079,  0.9999997 ,  0.06103631, -0.01724914],
        [ 0.14706229,  0.06103631,  1.0000001 ,  0.04374431],
        [-0.15708376, -0.01724914,  0.04374431,  1.0000001 ]],
       dtype=float32),
 100)

In [55]:
# Calcula el producto G = Z.T @ Z / (n-1) y verifica que coincide con tu covarianza
G = z.T @ z / (n-1)
G

array([[ 0.99999994, -0.18085079,  0.14706229, -0.15708376],
       [-0.18085079,  0.9999997 ,  0.06103631, -0.01724914],
       [ 0.14706229,  0.06103631,  1.0000001 ,  0.04374431],
       [-0.15708376, -0.01724914,  0.04374431,  1.0000001 ]],
      dtype=float32)

In [56]:
# Usa where para crear una máscara booleana que marque días “anómalos” si algún sensor z-score |z|≥2 (pista: np.any por filas).

anomalous_mask = np.any(np.abs(z) >= 2, axis = 1)

indices = np.where(anomalous_mask)[0]



In [57]:
# Extra: añade a cada fila un vector patrón [0.5, -0.5, 0, 1] via broadcasting y vuelve a detectar anómalos. Explica si cambia algo.
# 1) vector patrón (asegúrate del tipo)
pattern = np.array([0.5, -0.5, 0.0, 1.0], dtype=s.dtype)  # shape (4,)

# 2) suma por broadcasting: s tiene shape (100,4)
s2 = s + pattern   # shape (100,4) -- broadcasting por filas

# 3) recalcula z-scores (igual que antes)
mean2 = np.mean(s2, axis=0)
std2  = np.std(s2, axis=0)           # usa ddof=0 si antes lo usaste así
z2    = (s2 - mean2) / std2

# 4) detecta anomalías de nuevo
anomalous_mask2   = np.any(np.abs(z2) >= 2, axis=1)
indices2          = np.where(anomalous_mask2)[0]

# 5) compara con la máscara/índices anteriores
print("Anomalous original:", anomalous_mask.sum(), "days")
print("Anomalous after pattern:", anomalous_mask2.sum(), "days")
print("Masks equal (allclose/bool equal):", np.array_equal(anomalous_mask, anomalous_mask2))
print("Indices equal (first 20):", np.array_equal(indices[:20], indices2[:20]))


Anomalous original: 0 days
Anomalous after pattern: 0 days
Masks equal (allclose/bool equal): True
Indices equal (first 20): True
